from enum import Enum

class NotificationType(str, Enum):
    MESSAGES_READ = "MESSAGES_READ_NOTIFICATION"
    NEW_MESSAGE = "NEW_MESSAGE_NOTIFICATION"
    NEW_CHATROOM_MESSAGE = "NEW_CHATROOM_MESSAGE_NOTIFICATION"
    TEAM_JOINED = "TEAM_JOINED_NOTIFICATION"
    TEAM_NEW_MEMBER = "TEAM_NEW_MEMBER_NOTIFICATION"
