upstream fastapi_app {
    server backend:8000;
    keepalive 32;
}

server {
    listen 80;
    server_name localhost;

    client_max_body_size 10M;

    # Servir imágenes dinámicas subidas por el admin
    location /media/ {
        alias /var/www/media/;
        sendfile on;
        tcp_nopush on;

        expires 30d;
        add_header Cache-Control "public, no-transform";
        add_header Access-Control-Allow-Origin *;

        # Seguridad: Solo servir formatos de imagen válidos
        location ~* \.(?:ico|gif|jpe?g|png|webp|svg)$ {
            try_files $uri =404;
        }
    }

    # API FastAPI y Swagger Docs
    location / {
        proxy_pass http://fastapi_app;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}
