# Mapeo dinámico para el handshake de WebSocket
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}
upstream fastapi_app {
    server backend:8000;
    keepalive 32;
}

upstream vite_app {
    server frontend:5173;
}

server {
    listen 80;
    server_name localhost;

    client_max_body_size 10M;

    # Servir imágenes dinámicas
    location /media/ {
        alias /var/www/media/;
        sendfile on;
        tcp_nopush on;
        expires 30d;
        add_header Cache-Control "public, no-transform";
        add_header Access-Control-Allow-Origin *;

        location ~* \.(?:ico|gif|jpe?g|png|webp|svg)$ {
            try_files $uri =404;
        }
    }

    # 2. WebSockets de FastAPI (/api/v1/ws/...)
    # El modificador '^~' obliga a Nginx a detener la búsqueda si coincide la ruta,
    # impidiendo que la expresión regular de la API REST de abajo lo atrape.
    location ^~ /api/v1/ws/ {
        proxy_pass http://fastapi_app;
        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;

        # Evita que Nginx cierre el chat por inactividad tras 60 segundos
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }

    # API FastAPI y Swagger Docs
    location ~ ^/(docs|openapi.json|api|auth)($|/) {
        proxy_pass http://fastapi_app;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
    }

    # Frontend Vite + Soporte de WebSocket (HMR)
    location / {
        proxy_pass http://vite_app;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
