"""añadir clases relacionadas a los equipos

Revision ID: 45b25249020b
Revises: 73cddd2314f6
Create Date: 2026-10-03 19:46:50.525644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45b25249020b'
down_revision: Union[str, Sequence[str], None] = '73cddd2314f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatroom',
    sa.Column('chatroom_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('chatroom_id', name=op.f('pk__chatroom'))
    )
    op.create_table('chatroom_member',
    sa.Column('chatroom_member_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chatroom_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chatroom_id'], ['chatroom.chatroom_id'], name=op.f('fk__chatroom_member__chatroom_id__chatroom')),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk__chatroom_member__user_id__user')),
    sa.PrimaryKeyConstraint('chatroom_member_id', name=op.f('pk__chatroom_member'))
    )
    op.create_table('region',
    sa.Column('region_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('videogame_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['videogame_id'], ['videogame.videogame_id'], name=op.f('fk__region__videogame_id__videogame')),
    sa.PrimaryKeyConstraint('region_id', name=op.f('pk__region'))
    )
    op.create_table('team',
    sa.Column('team_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('allow_other_regions', sa.Boolean(), nullable=False),
    sa.Column('videogame_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('min_rank_id', sa.Integer(), nullable=False),
    sa.Column('max_rank_id', sa.Integer(), nullable=False),
    sa.Column('chatroom_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chatroom_id'], ['chatroom.chatroom_id'], name=op.f('fk__team__chatroom_id__chatroom')),
    sa.ForeignKeyConstraint(['max_rank_id'], ['rank.rank_id'], name=op.f('fk__team__max_rank_id__rank')),
    sa.ForeignKeyConstraint(['min_rank_id'], ['rank.rank_id'], name=op.f('fk__team__min_rank_id__rank')),
    sa.ForeignKeyConstraint(['region_id'], ['region.region_id'], name=op.f('fk__team__region_id__region')),
    sa.ForeignKeyConstraint(['videogame_id'], ['videogame.videogame_id'], name=op.f('fk__team__videogame_id__videogame')),
    sa.PrimaryKeyConstraint('team_id', name=op.f('pk__team'))
    )
    op.create_table('team_member_role',
    sa.Column('team_member_role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], name=op.f('fk__team_member_role__team_id__team')),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk__team_member_role__user_id__user')),
    sa.PrimaryKeyConstraint('team_member_role_id', name=op.f('pk__team_member_role'))
    )
    with op.batch_alter_table('character') as batch_op:
        batch_op.alter_column('name',
                              existing_type=sa.TEXT(),
                              type_=sa.String(),
                              existing_nullable=False)
        batch_op.create_unique_constraint(
            'uq_videogame_character_name',
            ['videogame_id', 'name']
        )
    with op.batch_alter_table('character') as batch_op:
        batch_op.alter_column('icon_url',
                              existing_type=sa.TEXT(),
                              type_=sa.String(),
                              existing_nullable=False)
    with op.batch_alter_table('conversation') as batch_op:
        batch_op.create_unique_constraint('uq_users_chat', ['user_1_id', 'user_2_id'])
    with op.batch_alter_table('game_profile') as batch_op:
        batch_op.create_unique_constraint('uq_profile_x_videogame', ['player_id', 'videogame_id'])
    with op.batch_alter_table('game_profile_character_priority') as batch_op:
        batch_op.create_unique_constraint('uq_game_profile_character', ['game_profile_id', 'character_id'])
        batch_op.create_unique_constraint('uq_game_profile_preference', ['game_profile_id', 'priority'])
    with op.batch_alter_table('message') as batch_op:
        batch_op.alter_column('timestamp',
                              existing_type=sa.TEXT(),
                              type_=sa.DateTime(timezone=True),
                              existing_nullable=False)
        batch_op.alter_column('is_read',
                              existing_type=sa.INTEGER(),
                              type_=sa.Boolean(),
                              nullable=False)
    with op.batch_alter_table('rank') as batch_op:
        batch_op.alter_column('name',
                              existing_type=sa.TEXT(),
                              type_=sa.String(),
                              existing_nullable=False)
        batch_op.alter_column('icon_url',
                              existing_type=sa.TEXT(),
                              type_=sa.String(),
                              existing_nullable=False)
        batch_op.create_unique_constraint('uq_videogame_rank_name', ['videogame_id', 'name'])
        batch_op.create_unique_constraint('uq_videogame_rank_value', ['videogame_id', 'value'])
    with op.batch_alter_table('refresh_tokens') as batch_op:
        batch_op.alter_column('user_role',
                              existing_type=sa.TEXT(),
                              type_=sa.String(length=20),
                              existing_nullable=False)
        batch_op.alter_column('jti',
                              existing_type=sa.TEXT(),
                              type_=sa.String(length=64),
                              existing_nullable=False)
        batch_op.alter_column('revoked',
                              existing_type=sa.INTEGER(),
                              type_=sa.Boolean(),
                              existing_nullable=False)
        batch_op.create_index(op.f('ix__refresh_tokens__jti'), ['jti'], unique=True)
        batch_op.create_index(op.f('ix__refresh_tokens__user_id'), ['user_id'], unique=False)
    with op.batch_alter_table('role') as batch_op:
        batch_op.alter_column('name',
                              existing_type=sa.TEXT(),
                              type_=sa.String(),
                              existing_nullable=False)
        batch_op.alter_column('icon_url',
                              existing_type=sa.TEXT(),
                              type_=sa.String(),
                              existing_nullable=False)
        batch_op.create_unique_constraint('uq_videogame_role_name', ['videogame_id', 'name'])
    with op.batch_alter_table('role_profile') as batch_op:
        batch_op.create_unique_constraint('uq_profile_role', ['game_profile_id', 'role_id'])
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column('name',
                              existing_type=sa.TEXT(),
                              type_=sa.String(),
                              existing_nullable=False)
        batch_op.alter_column('username',
                              existing_type=sa.TEXT(),
                              type_=sa.String(),
                              nullable=False)
        batch_op.alter_column('mail',
                              existing_type=sa.TEXT(),
                              type_=sa.String(),
                              existing_nullable=True)
        batch_op.alter_column('password_hash',
                              existing_type=sa.TEXT(),
                              type_=sa.String(),
                              existing_nullable=True)
        batch_op.alter_column('role',
                              existing_type=sa.TEXT(),
                              type_=sa.String(),
                              existing_nullable=False)
        batch_op.alter_column('icon_url',
                              existing_type=sa.TEXT(),
                              type_=sa.String(),
                              existing_nullable=True)
        batch_op.create_unique_constraint(op.f('uq__user__mail'), ['mail'])
        batch_op.create_unique_constraint(op.f('uq__user__username'), ['username'])
    with op.batch_alter_table('videogame') as batch_op:
        batch_op.alter_column('name',
                              existing_type=sa.TEXT(),
                              type_=sa.String(),
                              existing_nullable=False)
        batch_op.alter_column('icon_url',
                              existing_type=sa.TEXT(),
                              type_=sa.String(),
                              existing_nullable=False)
        batch_op.create_unique_constraint(op.f('uq__videogame__name'), ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videogame') as batch_op:
        batch_op.drop_constraint(op.f('uq__videogame__name'), type_='unique')
        batch_op.alter_column('icon_url',
                              existing_type=sa.String(),
                              type_=sa.TEXT(),
                              existing_nullable=False)
        batch_op.alter_column('name',
                              existing_type=sa.String(),
                              type_=sa.TEXT(),
                              existing_nullable=False)
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_constraint(op.f('uq__user__username'), type_='unique')
        batch_op.drop_constraint(op.f('uq__user__mail'), type_='unique')
        batch_op.alter_column('icon_url',
                              existing_type=sa.String(),
                              type_=sa.TEXT(),
                              existing_nullable=True)
        batch_op.alter_column('role',
                              existing_type=sa.String(),
                              type_=sa.TEXT(),
                              existing_nullable=False)
        batch_op.alter_column('password_hash',
                              existing_type=sa.String(),
                              type_=sa.TEXT(),
                              existing_nullable=True)
        batch_op.alter_column('mail',
                              existing_type=sa.String(),
                              type_=sa.TEXT(),
                              existing_nullable=True)
        batch_op.alter_column('username',
                              existing_type=sa.String(),
                              type_=sa.TEXT(),
                              nullable=True)
        batch_op.alter_column('name',
                              existing_type=sa.String(),
                              type_=sa.TEXT(),
                              existing_nullable=False)
    with op.batch_alter_table('role_profile') as batch_op:
        batch_op.drop_constraint('uq_profile_role', type_='unique')
    with op.batch_alter_table('role') as batch_op:
        batch_op.drop_constraint('uq_videogame_role_name', type_='unique')
        batch_op.alter_column('icon_url',
                              existing_type=sa.String(),
                              type_=sa.TEXT(),
                              existing_nullable=False)
        batch_op.alter_column('name',
                              existing_type=sa.String(),
                              type_=sa.TEXT(),
                              existing_nullable=False)
    with op.batch_alter_table('refresh_tokens') as batch_op:
        batch_op.drop_index(op.f('ix__refresh_tokens__user_id'))
        batch_op.drop_index(op.f('ix__refresh_tokens__jti'))
        batch_op.alter_column('revoked',
                              existing_type=sa.Boolean(),
                              type_=sa.INTEGER(),
                              existing_nullable=False)
        batch_op.alter_column('jti',
                              existing_type=sa.String(length=64),
                              type_=sa.TEXT(),
                              existing_nullable=False)
        batch_op.alter_column('user_role',
                              existing_type=sa.String(length=20),
                              type_=sa.TEXT(),
                              existing_nullable=False)
    with op.batch_alter_table('rank') as batch_op:
        batch_op.drop_constraint('uq_videogame_rank_value', type_='unique')
        batch_op.drop_constraint('uq_videogame_rank_name', type_='unique')
        batch_op.alter_column('icon_url',
                              existing_type=sa.String(),
                              type_=sa.TEXT(),
                              existing_nullable=False)
        batch_op.alter_column('name',
                              existing_type=sa.String(),
                              type_=sa.TEXT(),
                              existing_nullable=False)
    with op.batch_alter_table('message') as batch_op:
        batch_op.alter_column('is_read',
                              existing_type=sa.Boolean(),
                              type_=sa.INTEGER(),
                              nullable=True)
        batch_op.alter_column('timestamp',
                              existing_type=sa.DateTime(timezone=True),
                              type_=sa.TEXT(),
                              existing_nullable=False)
    with op.batch_alter_table('game_profile_character_priority') as batch_op:
        batch_op.drop_constraint('uq_game_profile_preference', type_='unique')
        batch_op.drop_constraint('uq_game_profile_character', type_='unique')
    with op.batch_alter_table('game_profile') as batch_op:
        batch_op.drop_constraint('uq_profile_x_videogame', type_='unique')
    with op.batch_alter_table('conversation') as batch_op:
        batch_op.drop_constraint('uq_users_chat', type_='unique')
    with op.batch_alter_table('character') as batch_op:
        batch_op.drop_constraint('uq_videogame_character_name', type_='unique')
        batch_op.alter_column('icon_url',
                              existing_type=sa.String(),
                              type_=sa.TEXT(),
                              existing_nullable=False)
        batch_op.alter_column('name',
                              existing_type=sa.String(),
                              type_=sa.TEXT(),
                              existing_nullable=False)
    op.drop_table('team_member_role')
    op.drop_table('team')
    op.drop_table('region')
    op.drop_table('chatroom_member')
    op.drop_table('chatroom')
    # ### end Alembic commands ###
