"""modified_team_to_add_description

Revision ID: 4bd71e0da2e8
Revises: baca19578843
Create Date: 2026-10-05 04:07:17.286800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bd71e0da2e8'
down_revision: Union[str, Sequence[str], None] = 'baca19578843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk__game_profile__region_id__region'), 'region', ['region_id'], ['region_id'])

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('conversation_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('conversation_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('game_profile', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk__game_profile__region_id__region'), type_='foreignkey')
        batch_op.drop_column('region_id')

    # ### end Alembic commands ###
