"""initial_schema

Revision ID: 73cddd2314f6
Revises: 
Create Date: 2026-10-03 18:54:55.305846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73cddd2314f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('character', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('character', 'icon_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_unique_constraint('uq_videogame_character_name', 'character', ['videogame_id', 'name'])
    op.create_unique_constraint('uq_users_chat', 'conversation', ['user_1_id', 'user_2_id'])
    op.create_unique_constraint('uq_profile_x_videogame', 'game_profile', ['player_id', 'videogame_id'])
    op.create_unique_constraint('uq_game_profile_character', 'game_profile_character_priority', ['game_profile_id', 'character_id'])
    op.create_unique_constraint('uq_game_profile_preference', 'game_profile_character_priority', ['game_profile_id', 'priority'])
    op.alter_column('message', 'timestamp',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('message', 'is_read',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False)
    op.alter_column('rank', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('rank', 'icon_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_unique_constraint('uq_videogame_rank_name', 'rank', ['videogame_id', 'name'])
    op.create_unique_constraint('uq_videogame_rank_value', 'rank', ['videogame_id', 'value'])
    op.alter_column('refresh_tokens', 'user_role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'jti',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'revoked',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.create_index(op.f('ix__refresh_tokens__jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix__refresh_tokens__user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.alter_column('role', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('role', 'icon_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_unique_constraint('uq_videogame_role_name', 'role', ['videogame_id', 'name'])
    op.create_unique_constraint('uq_profile_role', 'role_profile', ['game_profile_id', 'role_id'])
    op.alter_column('user', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('user', 'mail',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('user', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('user', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user', 'icon_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_unique_constraint(op.f('uq__user__mail'), 'user', ['mail'])
    op.create_unique_constraint(op.f('uq__user__username'), 'user', ['username'])
    op.alter_column('videogame', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('videogame', 'icon_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq__videogame__name'), 'videogame', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__videogame__name'), 'videogame', type_='unique')
    op.alter_column('videogame', 'icon_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('videogame', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(op.f('uq__user__username'), 'user', type_='unique')
    op.drop_constraint(op.f('uq__user__mail'), 'user', type_='unique')
    op.alter_column('user', 'icon_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user', 'role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user', 'mail',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user', 'username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('uq_profile_role', 'role_profile', type_='unique')
    op.drop_constraint('uq_videogame_role_name', 'role', type_='unique')
    op.alter_column('role', 'icon_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('role', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix__refresh_tokens__user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix__refresh_tokens__jti'), table_name='refresh_tokens')
    op.alter_column('refresh_tokens', 'revoked',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'jti',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'user_role',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('uq_videogame_rank_value', 'rank', type_='unique')
    op.drop_constraint('uq_videogame_rank_name', 'rank', type_='unique')
    op.alter_column('rank', 'icon_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('rank', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('message', 'is_read',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('message', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('uq_game_profile_preference', 'game_profile_character_priority', type_='unique')
    op.drop_constraint('uq_game_profile_character', 'game_profile_character_priority', type_='unique')
    op.drop_constraint('uq_profile_x_videogame', 'game_profile', type_='unique')
    op.drop_constraint('uq_users_chat', 'conversation', type_='unique')
    op.drop_constraint('uq_videogame_character_name', 'character', type_='unique')
    op.alter_column('character', 'icon_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('character', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
