"""added_capacitiy_to_team_made_region_nullable

Revision ID: 87556bbe8c18
Revises: 99d46c3b0b4e
Create Date: 2026-10-04 04:35:26.316694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87556bbe8c18'
down_revision: Union[str, Sequence[str], None] = '99d46c3b0b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_capacity', sa.Integer(), nullable=False))
        batch_op.alter_column('region_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('region_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('max_capacity')

    # ### end Alembic commands ###
