"""initial_schema

Revision ID: 99d46c3b0b4e
Revises: 
Create Date: 2026-10-03 23:53:40.863233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99d46c3b0b4e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('conversation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('conversation_id', name=op.f('pk__conversation'))
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('mail', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('last_connection', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk__user')),
    sa.UniqueConstraint('mail', name=op.f('uq__user__mail')),
    sa.UniqueConstraint('username', name=op.f('uq__user__username'))
    )
    op.create_table('videogame',
    sa.Column('videogame_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon_url', sa.String(), nullable=False),
    sa.Column('rank_per_role', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('videogame_id', name=op.f('pk__videogame')),
    sa.UniqueConstraint('name', name=op.f('uq__videogame__name'))
    )
    op.create_table('character',
    sa.Column('character_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('videogame_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['videogame_id'], ['videogame.videogame_id'], name=op.f('fk__character__videogame_id__videogame')),
    sa.PrimaryKeyConstraint('character_id', name=op.f('pk__character')),
    sa.UniqueConstraint('videogame_id', 'name', name='uq_videogame_character_name')
    )
    op.create_table('conversation_member',
    sa.Column('conversation_member_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.conversation_id'], name=op.f('fk__conversation_member__conversation_id__conversation')),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk__conversation_member__user_id__user')),
    sa.PrimaryKeyConstraint('conversation_member_id', name=op.f('pk__conversation_member'))
    )
    op.create_table('game_profile',
    sa.Column('game_profile_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('videogame_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['user.user_id'], name=op.f('fk__game_profile__player_id__user')),
    sa.ForeignKeyConstraint(['videogame_id'], ['videogame.videogame_id'], name=op.f('fk__game_profile__videogame_id__videogame')),
    sa.PrimaryKeyConstraint('game_profile_id', name=op.f('pk__game_profile')),
    sa.UniqueConstraint('player_id', 'videogame_id', name='uq_profile_x_videogame')
    )
    op.create_table('message',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.conversation_id'], name=op.f('fk__message__conversation_id__conversation')),
    sa.ForeignKeyConstraint(['sender_id'], ['user.user_id'], name=op.f('fk__message__sender_id__user')),
    sa.PrimaryKeyConstraint('message_id', name=op.f('pk__message'))
    )
    op.create_table('rank',
    sa.Column('rank_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('videogame_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('icon_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['videogame_id'], ['videogame.videogame_id'], name=op.f('fk__rank__videogame_id__videogame')),
    sa.PrimaryKeyConstraint('rank_id', name=op.f('pk__rank')),
    sa.UniqueConstraint('videogame_id', 'name', name='uq_videogame_rank_name'),
    sa.UniqueConstraint('videogame_id', 'value', name='uq_videogame_rank_value')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_role', sa.String(length=20), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk__refresh_tokens__user_id__user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__refresh_tokens'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix__refresh_tokens__jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix__refresh_tokens__user_id'), ['user_id'], unique=False)

    op.create_table('region',
    sa.Column('region_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('videogame_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['videogame_id'], ['videogame.videogame_id'], name=op.f('fk__region__videogame_id__videogame')),
    sa.PrimaryKeyConstraint('region_id', name=op.f('pk__region'))
    )
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('videogame_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['videogame_id'], ['videogame.videogame_id'], name=op.f('fk__role__videogame_id__videogame')),
    sa.PrimaryKeyConstraint('role_id', name=op.f('pk__role')),
    sa.UniqueConstraint('videogame_id', 'name', name='uq_videogame_role_name')
    )
    op.create_table('game_profile_character_priority',
    sa.Column('character_priority_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_profile_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.character_id'], name=op.f('fk__game_profile_character_priority__character_id__character')),
    sa.ForeignKeyConstraint(['game_profile_id'], ['game_profile.game_profile_id'], name=op.f('fk__game_profile_character_priority__game_profile_id__game_profile')),
    sa.PrimaryKeyConstraint('character_priority_id', name=op.f('pk__game_profile_character_priority')),
    sa.UniqueConstraint('game_profile_id', 'character_id', name='uq_game_profile_character'),
    sa.UniqueConstraint('game_profile_id', 'priority', name='uq_game_profile_preference')
    )
    op.create_table('role_profile',
    sa.Column('role_profile_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_profile_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('rank_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_profile_id'], ['game_profile.game_profile_id'], name=op.f('fk__role_profile__game_profile_id__game_profile')),
    sa.ForeignKeyConstraint(['rank_id'], ['rank.rank_id'], name=op.f('fk__role_profile__rank_id__rank')),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], name=op.f('fk__role_profile__role_id__role')),
    sa.PrimaryKeyConstraint('role_profile_id', name=op.f('pk__role_profile')),
    sa.UniqueConstraint('game_profile_id', 'role_id', name='uq_profile_role')
    )
    op.create_table('team',
    sa.Column('team_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('allow_other_regions', sa.Boolean(), nullable=False),
    sa.Column('videogame_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('min_rank_id', sa.Integer(), nullable=False),
    sa.Column('max_rank_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.conversation_id'], name=op.f('fk__team__conversation_id__conversation')),
    sa.ForeignKeyConstraint(['max_rank_id'], ['rank.rank_id'], name=op.f('fk__team__max_rank_id__rank')),
    sa.ForeignKeyConstraint(['min_rank_id'], ['rank.rank_id'], name=op.f('fk__team__min_rank_id__rank')),
    sa.ForeignKeyConstraint(['region_id'], ['region.region_id'], name=op.f('fk__team__region_id__region')),
    sa.ForeignKeyConstraint(['videogame_id'], ['videogame.videogame_id'], name=op.f('fk__team__videogame_id__videogame')),
    sa.PrimaryKeyConstraint('team_id', name=op.f('pk__team'))
    )
    op.create_table('team_member_role',
    sa.Column('team_member_role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], name=op.f('fk__team_member_role__team_id__team')),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk__team_member_role__user_id__user')),
    sa.PrimaryKeyConstraint('team_member_role_id', name=op.f('pk__team_member_role'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_member_role')
    op.drop_table('team')
    op.drop_table('role_profile')
    op.drop_table('game_profile_character_priority')
    op.drop_table('role')
    op.drop_table('region')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix__refresh_tokens__user_id'))
        batch_op.drop_index(batch_op.f('ix__refresh_tokens__jti'))

    op.drop_table('refresh_tokens')
    op.drop_table('rank')
    op.drop_table('message')
    op.drop_table('game_profile')
    op.drop_table('conversation_member')
    op.drop_table('character')
    op.drop_table('videogame')
    op.drop_table('user')
    op.drop_table('conversation')
    # ### end Alembic commands ###
