"""added_last_read_message_id_to_conversation_member

Revision ID: a010572873c4
Revises: 4bd71e0da2e8
Create Date: 2026-10-05 08:03:34.851235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a010572873c4'
down_revision: Union[str, Sequence[str], None] = '4bd71e0da2e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_read_message_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_member', schema=None) as batch_op:
        batch_op.drop_column('last_read_message_id')

    # ### end Alembic commands ###
