"""multiple_changes_in_the_teams_structure_and_child_structures

Revision ID: baca19578843
Revises: 87556bbe8c18
Create Date: 2026-10-04 10:31:49.147551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baca19578843'
down_revision: Union[str, Sequence[str], None] = '87556bbe8c18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('max_capacity')

    with op.batch_alter_table('team_member_role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_role_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('game_role_id', sa.Integer(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint('uq_user_team', ['user_id', 'team_id'])
        batch_op.create_foreign_key(batch_op.f('fk__team_member_role__game_role_id__role'), 'role', ['game_role_id'], ['role_id'])
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_member_role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk__team_member_role__game_role_id__role'), type_='foreignkey')
        batch_op.drop_constraint('uq_user_team', type_='unique')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('game_role_id')
        batch_op.drop_column('team_role_id')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_capacity', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
